In [1]:
#Install vega_datasets and altair packages
%pip install altair vega_datasets

Requirement already satisfied: altair in c:\users\jason\anaconda3\lib\site-packages (5.1.2)
Requirement already satisfied: vega_datasets in c:\users\jason\anaconda3\lib\site-packages (0.9.0)
Requirement already satisfied: jinja2 in c:\users\jason\anaconda3\lib\site-packages (from altair) (3.1.2)
Requirement already satisfied: jsonschema>=3.0 in c:\users\jason\anaconda3\lib\site-packages (from altair) (4.17.3)
Requirement already satisfied: numpy in c:\users\jason\anaconda3\lib\site-packages (from altair) (1.24.3)
Requirement already satisfied: packaging in c:\users\jason\anaconda3\lib\site-packages (from altair) (23.1)
Requirement already satisfied: pandas>=0.25 in c:\users\jason\anaconda3\lib\site-packages (from altair) (2.0.3)
Requirement already satisfied: toolz in c:\users\jason\anaconda3\lib\site-packages (from altair) (0.12.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\jason\anaconda3\lib\site-packages (from jsonschema>=3.0->altair) (22.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\jason\anaconda3\lib\site-packages (from jsonschema>=3.0->altair) (0.18.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jason\anaconda3\lib\site-packages (from pandas>=0.25->altair) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\jason\anaconda3\lib\site-packages (from pandas>=0.25->altair) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\jason\anaconda3\lib\site-packages (from pandas>=0.25->altair) (2023.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\jason\anaconda3\lib\site-packages (from jinja2->altair) (2.1.1)
Requirement already satisfied: six>=1.5 in c:\users\jason\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.25->altair) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
#Install numpy for analysis 
%pip install numpy

Requirement already satisfied: numpy in c:\users\jason\anaconda3\lib\site-packages (1.24.3)
Note: you may need to restart the kernel to use updated packages.

In [3]:
#Install Geopandas to construct an interactive map from which countries will be selected
%pip install geopandas

Requirement already satisfied: geopandas in c:\users\jason\anaconda3\lib\site-packages (0.14.1)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: fiona>=1.8.21 in c:\users\jason\anaconda3\lib\site-packages (from geopandas) (1.9.5)
Requirement already satisfied: packaging in c:\users\jason\anaconda3\lib\site-packages (from geopandas) (23.1)
Requirement already satisfied: pandas>=1.4.0 in c:\users\jason\anaconda3\lib\site-packages (from geopandas) (2.0.3)
Requirement already satisfied: pyproj>=3.3.0 in c:\users\jason\anaconda3\lib\site-packages (from geopandas) (3.6.1)
Requirement already satisfied: shapely>=1.8.0 in c:\users\jason\anaconda3\lib\site-packages (from geopandas) (2.0.2)
Requirement already satisfied: attrs>=19.2.0 in c:\users\jason\anaconda3\lib\site-packages (from fiona>=1.8.21->geopandas) (22.1.0)
Requirement already satisfied: certifi in c:\users\jason\anaconda3\lib\site-packages (from fiona>=1.8.21->geopandas) (2023.7.22)
Requirement already satisfied: click~=8.0 in c:\users\jason\anaconda3\lib\site-packages (from fiona>=1.8.21->geopandas) (8.0.4)
Requirement already satisfied: click-plugins>=1.0 in c:\users\jason\anaconda3\lib\site-packages (from fiona>=1.8.21->geopandas) (1.1.1)
Requirement already satisfied: cligj>=0.5 in c:\users\jason\anaconda3\lib\site-packages (from fiona>=1.8.21->geopandas) (0.7.2)
Requirement already satisfied: six in c:\users\jason\anaconda3\lib\site-packages (from fiona>=1.8.21->geopandas) (1.16.0)
Requirement already satisfied: setuptools in c:\users\jason\anaconda3\lib\site-packages (from fiona>=1.8.21->geopandas) (68.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jason\anaconda3\lib\site-packages (from pandas>=1.4.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\jason\anaconda3\lib\site-packages (from pandas>=1.4.0->geopandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\jason\anaconda3\lib\site-packages (from pandas>=1.4.0->geopandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\jason\anaconda3\lib\site-packages (from pandas>=1.4.0->geopandas) (1.24.3)
Requirement already satisfied: colorama in c:\users\jason\anaconda3\lib\site-packages (from click~=8.0->fiona>=1.8.21->geopandas) (0.4.6)

In [4]:
# Import installed packages
import altair as alt
from vega_datasets import data
import geopandas as gpd
import pandas as pd
import numpy as np

In [5]:
# Load GeoData for generating world map
url = "https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_countries.zip"
countries_shape = gpd.read_file(url) # zipped shapefile
countries_shape = countries_shape[['NAME', 'CONTINENT', 'ISO_A3', 'geometry']]

# Data Loading and Preprocessing

In [6]:
# Load locally saved copy of the OECD Better Life Index excel into a pandas dataframe
# Skip the first 7 rows as these contain headers with metadata and other unnecessary information.
# Also skip the last row as this is just information on when the data was obtained,
df = pd.read_excel("OECD_betterLifeIndex.xlsx", skiprows=7, skipfooter=1)

In [7]:
df.head(50)

,Country,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,Australia,NaN,NaN,..,19.4,..,37433,528768,3.1,73,...,92,2.7,92,83.0,85,7.1,67,0.9,12.5,14.36
1,Austria,NaN,NaN,0.8,20.8,1.6,37001,309637,2.3,72,...,92,1.3,76,82.0,71,7.2,86,0.5,5.3,14.51
2,Belgium,NaN,NaN,0.7,20,2.1,34884,447607,2.4,65,...,79,2,88,82.1,74,6.8,56,1.1,4.3,15.52
3,Canada,NaN,NaN,0.2,22.9,2.6,34421,478240,3.8,70,...,90,2.9,68,82.1,89,7.0,78,1.2,3.3,14.57
4,Chile,NaN,NaN,9.4,18.4,1.9,..,135787,7,56,...,62,1.3,47,80.6,60,6.2,41,2.4,7.7,..
5,Colombia,NaN,NaN,12.3,..,1,..,..,..,58,...,82,1.4,53,76.7,80,5.7,50,23.1,23.7,..
6,Costa Rica,NaN,NaN,2.3,17,1.2,16517,..,..,55,...,87,1.8,66,80.5,73,6.3,47,10.0,22,..
7,Czech Republic,NaN,NaN,0.5,23.4,1.5,26664,..,2.3,74,...,89,1.6,62,79.3,62,6.9,77,0.7,4.5,..
8,Denmark,NaN,NaN,0.5,23.3,1.9,33774,149864,4.5,74,...,93,2,85,81.5,70,7.5,85,0.5,1.1,..
9,Estonia,NaN,NaN,5.7,17,1.7,23784,188627,5.4,74,...,86,2.7,64,78.8,57,6.5,79,1.9,2.2,14.98
10,Finland,NaN,NaN,0.4,23.1,1.9,33471,230032,2.2,72,...,97,2.2,69,82.1,68,7.9,88,1.2,3.6,15.17
11,France,NaN,NaN,0.5,20.7,1.8,34375,298639,3.1,65,...,78,2.1,75,82.9,67,6.7,74,0.4,7.7,16.2
12,Germany,NaN,NaN,0.1,20,1.8,38971,304317,1.4,77,...,91,1.8,76,81.4,66,7.3,76,0.4,3.9,15.62
13,Greece,NaN,NaN,0.4,21.8,1.2,20791,148323,21.7,56,...,67,1.8,58,81.7,79,5.8,69,1.0,4.5,15.03
14,Hungary,NaN,NaN,3.5,19.9,1.4,21026,150296,3.8,70,...,81,1.2,70,76.4,58,6.0,74,0.9,1.5,15.08
15,Iceland,NaN,NaN,0,..,1.6,..,..,1,78,...,97,2.1,81,83.2,77,7.6,85,0.3,11.7,..
16,Ireland,NaN,NaN,0.2,20.6,2.1,29488,370341,2.6,68,...,80,1.3,63,82.8,84,7.0,76,0.5,4.7,14.54
17,Israel,NaN,NaN,..,..,1.2,..,..,4.6,67,...,77,2.5,67,82.9,74,7.2,80,1.5,14.1,..
18,Italy,NaN,NaN,0.6,22.5,1.4,29431,295020,8.6,58,...,77,2.5,73,83.6,73,6.5,73,0.5,3.3,16.47
19,Japan,NaN,NaN,6.4,21.8,1.9,28872,294735,2.7,77,...,87,1.4,53,84.4,37,6.1,77,0.2,..,14.1
20,Korea,NaN,NaN,2.5,14.7,1.5,24590,362340,2.9,66,...,82,2.9,77,83.3,34,5.8,82,0.8,..,14.83
21,Latvia,NaN,NaN,11.2,20.8,1.2,19783,79245,6.3,72,...,83,2.2,55,75.5,47,6.2,72,3.7,1.6,..
22,Lithuania,NaN,NaN,11.8,18.4,1.5,26976,182039,..,72,...,83,2.4,57,76.4,46,6.4,62,2.5,1,..
23,Luxembourg,NaN,NaN,0.1,20.7,2,44773,941162,2.2,67,...,85,1.7,90,82.7,72,7.4,87,0.2,2.8,..
24,Mexico,NaN,NaN,25.9,17.8,1.1,16269,..,4,59,...,75,3.2,63,75.1,66,6.0,42,26.8,27,..
25,Netherlands,NaN,NaN,0.1,19.6,2,34984,248599,2.5,78,...,91,2.6,79,82.2,75,7.5,83,0.6,0.3,15.45
26,New Zealand,NaN,NaN,..,25,2.4,39024,514162,4.5,77,...,85,2.5,82,82.1,86,7.3,66,1.3,14,14.87
27,Norway,NaN,NaN,0,17.7,2.1,39144,268358,2.8,75,...,98,2.2,78,83.0,75,7.3,93,0.6,1.4,15.67
28,Poland,NaN,NaN,2.3,21.2,1.1,23675,233221,5,69,...,82,2.6,68,78.0,60,6.1,71,0.5,4.2,14.68
29,Portugal,NaN,NaN,0.9,19.6,1.7,24877,255303,8.1,69,...,89,1.5,49,81.8,50,5.8,83,0.7,5.6,..
30,Slovak Republic,NaN,NaN,1.5,27.4,1.1,21149,171425,8.8,68,...,81,3,66,77.8,65,6.5,76,0.8,4.2,..
31,Slovenia,NaN,NaN,0.2,18.2,1.6,25250,233286,5.9,71,...,93,2.5,53,81.6,67,6.5,91,0.4,5.6,..
32,Spain,NaN,NaN,0.3,21.7,1.9,27155,366534,15.8,62,...,76,1.8,72,83.9,75,6.5,80,0.7,2.5,15.75
33,Sweden,NaN,NaN,0,20.1,1.7,33730,..,4.4,75,...,97,2,87,83.2,76,7.3,79,1.1,0.9,..
34,Switzerland,NaN,NaN,0,21.4,1.9,39697,..,..,80,...,96,2.3,45,84.0,81,7.5,86,0.3,0.4,..
35,Türkiye,NaN,NaN,4.9,18.9,1,..,..,13,48,...,62,1.5,86,78.6,67,4.9,59,1.0,25,14.61
36,United Kingdom,NaN,NaN,0.5,23.2,2,33049,524422,3.3,75,...,82,3.1,68,81.3,73,6.8,78,0.2,10.8,14.94
37,United States,NaN,NaN,0.1,18.3,2.4,51147,684500,4.2,67,...,88,3.1,65,78.9,88,7.0,78,6.0,10.4,14.57
38,OECD - Total,NaN,NaN,3,20.5,1.7,30490,323960,5.1,66,...,84,2.1,69,81.0,68,6.7,74,2.6,10.2,15.07
39,Non-OECD Economies,Brazil,NaN,6.7,..,..,..,..,..,57,...,70,2.2,80,75.9,..,6.1,45,19.0,5.6,..
40,NaN,Russia,NaN,13.8,17.4,1,19546,..,..,70,...,62,..,68,73.2,43,5.5,64,4.8,0.1,..
41,NaN,South Africa,NaN,35.9,18.1,..,9338,..,..,39,...,72,..,66,64.2,..,4.9,40,13.7,15.4,..

In [8]:
# As the second and third columns are just used to reference Non-OECD countries; Brzail, Russia and South Africa. This column can be removed
# and aforementioned countries can have their names added to the first column.
modified_df = df.drop(df.columns[[1, 2]], axis = 1)

In [9]:
modified_df.head(50)

,Country,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,Australia,..,19.4,..,37433,528768,3.1,73,1,55206,...,92,2.7,92,83.0,85,7.1,67,0.9,12.5,14.36
1,Austria,0.8,20.8,1.6,37001,309637,2.3,72,1.3,53132,...,92,1.3,76,82.0,71,7.2,86,0.5,5.3,14.51
2,Belgium,0.7,20,2.1,34884,447607,2.4,65,2.3,54327,...,79,2,88,82.1,74,6.8,56,1.1,4.3,15.52
3,Canada,0.2,22.9,2.6,34421,478240,3.8,70,0.5,55342,...,90,2.9,68,82.1,89,7.0,78,1.2,3.3,14.57
4,Chile,9.4,18.4,1.9,..,135787,7,56,..,26729,...,62,1.3,47,80.6,60,6.2,41,2.4,7.7,..
5,Colombia,12.3,..,1,..,..,..,58,1.1,..,...,82,1.4,53,76.7,80,5.7,50,23.1,23.7,..
6,Costa Rica,2.3,17,1.2,16517,..,..,55,1.5,..,...,87,1.8,66,80.5,73,6.3,47,10.0,22,..
7,Czech Republic,0.5,23.4,1.5,26664,..,2.3,74,0.6,29885,...,89,1.6,62,79.3,62,6.9,77,0.7,4.5,..
8,Denmark,0.5,23.3,1.9,33774,149864,4.5,74,0.9,58430,...,93,2,85,81.5,70,7.5,85,0.5,1.1,..
9,Estonia,5.7,17,1.7,23784,188627,5.4,74,1.2,30720,...,86,2.7,64,78.8,57,6.5,79,1.9,2.2,14.98
10,Finland,0.4,23.1,1.9,33471,230032,2.2,72,1.2,46230,...,97,2.2,69,82.1,68,7.9,88,1.2,3.6,15.17
11,France,0.5,20.7,1.8,34375,298639,3.1,65,2.9,45581,...,78,2.1,75,82.9,67,6.7,74,0.4,7.7,16.2
12,Germany,0.1,20,1.8,38971,304317,1.4,77,1.2,53745,...,91,1.8,76,81.4,66,7.3,76,0.4,3.9,15.62
13,Greece,0.4,21.8,1.2,20791,148323,21.7,56,10.8,27207,...,67,1.8,58,81.7,79,5.8,69,1.0,4.5,15.03
14,Hungary,3.5,19.9,1.4,21026,150296,3.8,70,1.2,25409,...,81,1.2,70,76.4,58,6.0,74,0.9,1.5,15.08
15,Iceland,0,..,1.6,..,..,1,78,0.7,67488,...,97,2.1,81,83.2,77,7.6,85,0.3,11.7,..
16,Ireland,0.2,20.6,2.1,29488,370341,2.6,68,1.2,49474,...,80,1.3,63,82.8,84,7.0,76,0.5,4.7,14.54
17,Israel,..,..,1.2,..,..,4.6,67,0.2,39322,...,77,2.5,67,82.9,74,7.2,80,1.5,14.1,..
18,Italy,0.6,22.5,1.4,29431,295020,8.6,58,4.8,37769,...,77,2.5,73,83.6,73,6.5,73,0.5,3.3,16.47
19,Japan,6.4,21.8,1.9,28872,294735,2.7,77,0.8,38515,...,87,1.4,53,84.4,37,6.1,77,0.2,..,14.1
20,Korea,2.5,14.7,1.5,24590,362340,2.9,66,0,41960,...,82,2.9,77,83.3,34,5.8,82,0.8,..,14.83
21,Latvia,11.2,20.8,1.2,19783,79245,6.3,72,2.2,29876,...,83,2.2,55,75.5,47,6.2,72,3.7,1.6,..
22,Lithuania,11.8,18.4,1.5,26976,182039,..,72,2.5,31811,...,83,2.4,57,76.4,46,6.4,62,2.5,1,..
23,Luxembourg,0.1,20.7,2,44773,941162,2.2,67,1.7,65854,...,85,1.7,90,82.7,72,7.4,87,0.2,2.8,..
24,Mexico,25.9,17.8,1.1,16269,..,4,59,0.1,16230,...,75,3.2,63,75.1,66,6.0,42,26.8,27,..
25,Netherlands,0.1,19.6,2,34984,248599,2.5,78,0.9,58828,...,91,2.6,79,82.2,75,7.5,83,0.6,0.3,15.45
26,New Zealand,..,25,2.4,39024,514162,4.5,77,0.4,45269,...,85,2.5,82,82.1,86,7.3,66,1.3,14,14.87
27,Norway,0,17.7,2.1,39144,268358,2.8,75,0.9,55780,...,98,2.2,78,83.0,75,7.3,93,0.6,1.4,15.67
28,Poland,2.3,21.2,1.1,23675,233221,5,69,0.6,32527,...,82,2.6,68,78.0,60,6.1,71,0.5,4.2,14.68
29,Portugal,0.9,19.6,1.7,24877,255303,8.1,69,2.3,28410,...,89,1.5,49,81.8,50,5.8,83,0.7,5.6,..
30,Slovak Republic,1.5,27.4,1.1,21149,171425,8.8,68,3,23619,...,81,3,66,77.8,65,6.5,76,0.8,4.2,..
31,Slovenia,0.2,18.2,1.6,25250,233286,5.9,71,1.9,41445,...,93,2.5,53,81.6,67,6.5,91,0.4,5.6,..
32,Spain,0.3,21.7,1.9,27155,366534,15.8,62,5,37922,...,76,1.8,72,83.9,75,6.5,80,0.7,2.5,15.75
33,Sweden,0,20.1,1.7,33730,..,4.4,75,1,47020,...,97,2,87,83.2,76,7.3,79,1.1,0.9,..
34,Switzerland,0,21.4,1.9,39697,..,..,80,1.7,64824,...,96,2.3,45,84.0,81,7.5,86,0.3,0.4,..
35,Türkiye,4.9,18.9,1,..,..,13,48,3.3,..,...,62,1.5,86,78.6,67,4.9,59,1.0,25,14.61
36,United Kingdom,0.5,23.2,2,33049,524422,3.3,75,0.9,47147,...,82,3.1,68,81.3,73,6.8,78,0.2,10.8,14.94
37,United States,0.1,18.3,2.4,51147,684500,4.2,67,0.5,69392,...,88,3.1,65,78.9,88,7.0,78,6.0,10.4,14.57
38,OECD - Total,3,20.5,1.7,30490,323960,5.1,66,1.3,49165,...,84,2.1,69,81.0,68,6.7,74,2.6,10.2,15.07
39,Non-OECD Economies,6.7,..,..,..,..,..,57,..,..,...,70,2.2,80,75.9,..,6.1,45,19.0,5.6,..
40,NaN,13.8,17.4,1,19546,..,..,70,1.1,..,...,62,..,68,73.2,43,5.5,64,4.8,0.1,..
41,NaN,35.9,18.1,..,9338,..,..,39,17.9,..,...,72,..,66,64.2,..,4.9,40,13.7,15.4,..

In [10]:
# Assign Brazil, Russia, South Africa country names in column for their rows.
brazil_row = 39
russia_row = 40
safrica_row = 41
modified_df.iloc[brazil_row, 0] = "Brazil"
modified_df.iloc[russia_row, 0] = "Russia"
modified_df.iloc[safrica_row, 0] = "South Africa"

In [12]:
modified_df.head(50)

,Country,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,Australia,..,19.4,..,37433,528768,3.1,73,1,55206,...,92,2.7,92,83.0,85,7.1,67,0.9,12.5,14.36
1,Austria,0.8,20.8,1.6,37001,309637,2.3,72,1.3,53132,...,92,1.3,76,82.0,71,7.2,86,0.5,5.3,14.51
2,Belgium,0.7,20,2.1,34884,447607,2.4,65,2.3,54327,...,79,2,88,82.1,74,6.8,56,1.1,4.3,15.52
3,Canada,0.2,22.9,2.6,34421,478240,3.8,70,0.5,55342,...,90,2.9,68,82.1,89,7.0,78,1.2,3.3,14.57
4,Chile,9.4,18.4,1.9,..,135787,7,56,..,26729,...,62,1.3,47,80.6,60,6.2,41,2.4,7.7,..
5,Colombia,12.3,..,1,..,..,..,58,1.1,..,...,82,1.4,53,76.7,80,5.7,50,23.1,23.7,..
6,Costa Rica,2.3,17,1.2,16517,..,..,55,1.5,..,...,87,1.8,66,80.5,73,6.3,47,10.0,22,..
7,Czech Republic,0.5,23.4,1.5,26664,..,2.3,74,0.6,29885,...,89,1.6,62,79.3,62,6.9,77,0.7,4.5,..
8,Denmark,0.5,23.3,1.9,33774,149864,4.5,74,0.9,58430,...,93,2,85,81.5,70,7.5,85,0.5,1.1,..
9,Estonia,5.7,17,1.7,23784,188627,5.4,74,1.2,30720,...,86,2.7,64,78.8,57,6.5,79,1.9,2.2,14.98
10,Finland,0.4,23.1,1.9,33471,230032,2.2,72,1.2,46230,...,97,2.2,69,82.1,68,7.9,88,1.2,3.6,15.17
11,France,0.5,20.7,1.8,34375,298639,3.1,65,2.9,45581,...,78,2.1,75,82.9,67,6.7,74,0.4,7.7,16.2
12,Germany,0.1,20,1.8,38971,304317,1.4,77,1.2,53745,...,91,1.8,76,81.4,66,7.3,76,0.4,3.9,15.62
13,Greece,0.4,21.8,1.2,20791,148323,21.7,56,10.8,27207,...,67,1.8,58,81.7,79,5.8,69,1.0,4.5,15.03
14,Hungary,3.5,19.9,1.4,21026,150296,3.8,70,1.2,25409,...,81,1.2,70,76.4,58,6.0,74,0.9,1.5,15.08
15,Iceland,0,..,1.6,..,..,1,78,0.7,67488,...,97,2.1,81,83.2,77,7.6,85,0.3,11.7,..
16,Ireland,0.2,20.6,2.1,29488,370341,2.6,68,1.2,49474,...,80,1.3,63,82.8,84,7.0,76,0.5,4.7,14.54
17,Israel,..,..,1.2,..,..,4.6,67,0.2,39322,...,77,2.5,67,82.9,74,7.2,80,1.5,14.1,..
18,Italy,0.6,22.5,1.4,29431,295020,8.6,58,4.8,37769,...,77,2.5,73,83.6,73,6.5,73,0.5,3.3,16.47
19,Japan,6.4,21.8,1.9,28872,294735,2.7,77,0.8,38515,...,87,1.4,53,84.4,37,6.1,77,0.2,..,14.1
20,Korea,2.5,14.7,1.5,24590,362340,2.9,66,0,41960,...,82,2.9,77,83.3,34,5.8,82,0.8,..,14.83
21,Latvia,11.2,20.8,1.2,19783,79245,6.3,72,2.2,29876,...,83,2.2,55,75.5,47,6.2,72,3.7,1.6,..
22,Lithuania,11.8,18.4,1.5,26976,182039,..,72,2.5,31811,...,83,2.4,57,76.4,46,6.4,62,2.5,1,..
23,Luxembourg,0.1,20.7,2,44773,941162,2.2,67,1.7,65854,...,85,1.7,90,82.7,72,7.4,87,0.2,2.8,..
24,Mexico,25.9,17.8,1.1,16269,..,4,59,0.1,16230,...,75,3.2,63,75.1,66,6.0,42,26.8,27,..
25,Netherlands,0.1,19.6,2,34984,248599,2.5,78,0.9,58828,...,91,2.6,79,82.2,75,7.5,83,0.6,0.3,15.45
26,New Zealand,..,25,2.4,39024,514162,4.5,77,0.4,45269,...,85,2.5,82,82.1,86,7.3,66,1.3,14,14.87
27,Norway,0,17.7,2.1,39144,268358,2.8,75,0.9,55780,...,98,2.2,78,83.0,75,7.3,93,0.6,1.4,15.67
28,Poland,2.3,21.2,1.1,23675,233221,5,69,0.6,32527,...,82,2.6,68,78.0,60,6.1,71,0.5,4.2,14.68
29,Portugal,0.9,19.6,1.7,24877,255303,8.1,69,2.3,28410,...,89,1.5,49,81.8,50,5.8,83,0.7,5.6,..
30,Slovak Republic,1.5,27.4,1.1,21149,171425,8.8,68,3,23619,...,81,3,66,77.8,65,6.5,76,0.8,4.2,..
31,Slovenia,0.2,18.2,1.6,25250,233286,5.9,71,1.9,41445,...,93,2.5,53,81.6,67,6.5,91,0.4,5.6,..
32,Spain,0.3,21.7,1.9,27155,366534,15.8,62,5,37922,...,76,1.8,72,83.9,75,6.5,80,0.7,2.5,15.75
33,Sweden,0,20.1,1.7,33730,..,4.4,75,1,47020,...,97,2,87,83.2,76,7.3,79,1.1,0.9,..
34,Switzerland,0,21.4,1.9,39697,..,..,80,1.7,64824,...,96,2.3,45,84.0,81,7.5,86,0.3,0.4,..
35,Türkiye,4.9,18.9,1,..,..,13,48,3.3,..,...,62,1.5,86,78.6,67,4.9,59,1.0,25,14.61
36,United Kingdom,0.5,23.2,2,33049,524422,3.3,75,0.9,47147,...,82,3.1,68,81.3,73,6.8,78,0.2,10.8,14.94
37,United States,0.1,18.3,2.4,51147,684500,4.2,67,0.5,69392,...,88,3.1,65,78.9,88,7.0,78,6.0,10.4,14.57
38,OECD - Total,3,20.5,1.7,30490,323960,5.1,66,1.3,49165,...,84,2.1,69,81.0,68,6.7,74,2.6,10.2,15.07
39,Brazil,6.7,..,..,..,..,..,57,..,..,...,70,2.2,80,75.9,..,6.1,45,19.0,5.6,..
40,Russia,13.8,17.4,1,19546,..,..,70,1.1,..,...,62,..,68,73.2,43,5.5,64,4.8,0.1,..
41,South Africa,35.9,18.1,..,9338,..,..,39,17.9,..,...,72,..,66,64.2,..,4.9,40,13.7,15.4,..

In [13]:
# Create MultiIndex headers so that each column can have a heading denoting unit, indicator, and indicator group.
# For example:
# Housing Expenditure is the indicator
# Belonging to indicator group 'Housing' (another indicator in this group would be 'Rooms per person')
# Measured in Unit 'Percentage'
indicator_groups = ['Housing', 'Income', 'Jobs', 'Community', 'Education', 'Environment', 'Civic Engagement', 'Health', 'Life Satisfaction', 'Safety', 'Work-Life Balance']
indicators = ['Dwellings w/o basic facilities',
             'Housing expenditure',
             'Rooms per person',
             'Household net adjusted disposable income',
             'Household net wealth',
             'Labour market insecurity',
             'Employment rate',
             'Long-term unemployment rate',
             'Personal earnings',
             'Quality of support network',
             'Educational attainment',
             'Student skills',
             'Years in education',
             'Air pollution',
             'Water quality',
             'Stakeholder engagement for developing regulations',
             'Voter turnout',
             'Life expectancy',
             'Self-reported health',
             'Life satisfaction',
             'Feeling safe walking alone at night',
             'Homicide rate',
             'Employees working very long hours',
             'Leisure and personal care time']
units = ['Percentage', 'Ratio', 'US Dollar', 'Average Score', 'Micrograms per m^3', 'Hours', 'Years']

# Dictionary mapping the unit to each indicator
unit_mapping = {
    'Percentage': ['Dwellings w/o basic facilities', 'Housing expenditure', 'Labour market insecurity', 'Employment rate', 'Long-term unemployment rate', 'Quality of support network', 'Educational attainment', 'Voter turnout', 'Feeling safe walking alone at night', 'Employees working very long hours', 'Water quality', 'Self-reported health'],
    'Ratio': ['Rooms per person', 'Homicide rate'],
    'US Dollar': ['Household net adjusted disposable income', 'Household net wealth', 'Personal earnings'],
    'Average Score': ['Stakeholder engagement for developing regulations', 'Life satisfaction', 'Student skills'],
    'Micrograms per m^3': ['Air pollution'],
    'Hours': ['Leisure and personal care time'],
    'Years' : ['Years in education', 'Life expectancy']
}

group_mapping = {
    'Housing' : ['Dwellings w/o basic facilities',
                 'Housing expenditure',
                 'Rooms per person'],
    'Income' : ['Household net adjusted disposable income',
                'Household net wealth'],
    'Jobs' : ['Labour market insecurity',
             'Employment rate',
             'Long-term unemployment rate',
             'Personal earnings'],
    'Community' : ['Quality of support network'],
    'Education' : ['Educational attainment',
                   'Student skills',
                   'Years in education'],
    'Environment' : ['Air pollution',
                     'Water quality'],
    'Civic Engagement' : ['Stakeholder engagement for developing regulations',
                          'Voter turnout'],
    'Health' : ['Life expectancy',
               'Self-reported health'],
    'Life Satisfaction' : ['Life satisfaction'],
    'Safety' : ['Feeling safe walking alone at night',
                'Homicide rate'],
    'Work-Life Balance' : ['Employees working very long hours',
                           'Leisure and personal care time']
}

# Create tuples which will be the MultiIndex headers
headers = []
for group, indicators in group_mapping.items():
    for indicator in indicators:
        for unit, list_of_indicators in unit_mapping.items():
            if indicator in list_of_indicators:
                headers.append((group, indicator, unit))
# Create 'multi-level' header for countries column
country_header = [('Country', '', '')]
# Create 'multi-level' header for colours column
colour_header = [('Colour', '', '')]
# Create colour column
modified_df['Colour'] = None
# Create MultiIndex from the tuples and country header
multi_index = pd.MultiIndex.from_tuples((country_header + headers + colour_header), names=['Group', 'Indicator', 'Unit'])

## Assign MuliIntext to modified dataframe
modified_df.columns = multi_index
modified_df.head()

Group        Country                        Housing                      \
Indicator            Dwellings w/o basic facilities Housing expenditure
Unit                                     Percentage          Percentage
0          Australia                             ..                19.4
1            Austria                            0.8                20.8
2            Belgium                            0.7                  20
3             Canada                            0.2                22.9
4              Chile                            9.4                18.4

Group                                                        Income  \
Indicator Rooms per person Household net adjusted disposable income
Unit                 Ratio                                US Dollar
0                       ..                                    37433
1                      1.6                                    37001
2                      2.1                                    34884
3                      2.6                                    34421
4                      1.9                                       ..

Group                                              Jobs                  \
Indicator Household net wealth Labour market insecurity Employment rate
Unit                 US Dollar               Percentage      Percentage
0                       528768                      3.1              73
1                       309637                      2.3              72
2                       447607                      2.4              65
3                       478240                      3.8              70
4                       135787                        7              56

Group                                                    ...  \
Indicator Long-term unemployment rate Personal earnings  ...
Unit                       Percentage         US Dollar  ...
0                                   1             55206  ...
1                                 1.3             53132  ...
2                                 2.3             54327  ...
3                                 0.5             55342  ...
4                                  ..             26729  ...

Group                                      Civic Engagement                \
Indicator Stakeholder engagement for developing regulations Voter turnout
Unit                                          Average Score    Percentage
0                                                       2.7            92
1                                                       1.3            76
2                                                         2            88
3                                                       2.9            68
4                                                       1.3            47

Group              Health                      Life Satisfaction  \
Indicator Life expectancy Self-reported health Life satisfaction
Unit                Years           Percentage     Average Score
0                    83.0                   85               7.1
1                    82.0                   71               7.2
2                    82.1                   74               6.8
3                    82.1                   89               7.0
4                    80.6                   60               6.2

Group                                  Safety                \
Indicator Feeling safe walking alone at night Homicide rate
Unit                               Percentage         Ratio
0                                          67           0.9
1                                          86           0.5
2                                          56           1.1
3                                          78           1.2
4                                          41           2.4

Group                     Work-Life Balance                                 \
Indicator Employees working very long hours Leisure and personal care time
Unit                             Percentage                          Hours
0                                      12.5                          14.36
1                                       5.3                          14.51
2                                       4.3                          15.52
3                                       3.3                          14.57
4                                       7.7                             ..

Group     Colour
Indicator
Unit
0           None
1           None
2           None
3           None
4           None

[5 rows x 26 columns]

In [14]:
# Rename some country names to match with countries_shapes for the geodata
modified_df['Country'] = modified_df['Country'].replace({'Czech Republic':'Czechia','Korea':'South Korea','Slovak Republic':'Slovakia','Türkiye':'Turkey','United States':'United States of America'})

# Drop OECD row
modified_df = modified_df.drop(38)

In [15]:
# A List of 41 disticint colours. However, some are very visually similar to each other. 
# It is understood that the recommend number of colours for ease of visualization of categorical should be under 12 from https://spectrum.adobe.com/page/color-for-data-visualization/
# as exceeding this will be hard to easily understand, however i aim to give the user the option of countries to select, should only be visually overloaded when many countries are selected
# but in case all are, i still need distinct colours for 41 countries.

distinct_colours = [
    "#FF0000",  # Red
    "#0000FF",  # Blue
    "#008000",  # Green
    "#800080",  # Purple
    "#FFA500",  # Orange
    "#FFFF00",  # Yellow
    "#00FFFF",  # Cyan
    "#FFC0CB",  # Pink
    "#A52A2A",  # Brown
    "#800000",  # Maroon
    "#808000",  # Olive
    "#808080",  # Grey
    "#00FF00",  # Lime
    "#000080",  # Navy
    "#FF00FF",  # Magenta
    "#C0C0C0",  # Silver
    "#008080",  # Teal
    "#FFD700",  # Gold
    "#4B0082",  # Indigo
    "#708090",  # Slate Grey
    "#FA8072",  # Salmon
    "#2E8B57",  # Sea Green
    "#6A5ACD",  # Slate Blue
    "#20B2AA",  # Light Sea Green
    "#FF6347",  # Tomato
    "#7FFFD4",  # Aquamarine
    "#D2691E",  # Chocolate
    "#6495ED",  # Cornflower Blue
    "#DC143C",  # Crimson
    "#008B8B",  # Dark Cyan
    "#B8860B",  # Dark Goldenrod
    "#006400",  # Dark Green
    "#BDB76B",  # Dark Khaki
    "#8B008B",  # Dark Magenta
    "#556B2F",  # Dark Olive Green
    "#FF8C00",  # Dark Orange
    "#9932CC",  # Dark Orchid
    "#8B0000",  # Dark Red
    "#E9967A",  # Dark Salmon
    "#9400D3",  # Dark Violet
    "#FF1493",  # Deep Pink
    "#00CED1",  # Dark Turquoise
    "#DAA520"   # Goldenrod
]

modified_df.head()

Group        Country                        Housing                      \
Indicator            Dwellings w/o basic facilities Housing expenditure
Unit                                     Percentage          Percentage
0          Australia                             ..                19.4
1            Austria                            0.8                20.8
2            Belgium                            0.7                  20
3             Canada                            0.2                22.9
4              Chile                            9.4                18.4

Group                                                        Income  \
Indicator Rooms per person Household net adjusted disposable income
Unit                 Ratio                                US Dollar
0                       ..                                    37433
1                      1.6                                    37001
2                      2.1                                    34884
3                      2.6                                    34421
4                      1.9                                       ..

Group                                              Jobs                  \
Indicator Household net wealth Labour market insecurity Employment rate
Unit                 US Dollar               Percentage      Percentage
0                       528768                      3.1              73
1                       309637                      2.3              72
2                       447607                      2.4              65
3                       478240                      3.8              70
4                       135787                        7              56

Group                                                    ...  \
Indicator Long-term unemployment rate Personal earnings  ...
Unit                       Percentage         US Dollar  ...
0                                   1             55206  ...
1                                 1.3             53132  ...
2                                 2.3             54327  ...
3                                 0.5             55342  ...
4                                  ..             26729  ...

Group                                      Civic Engagement                \
Indicator Stakeholder engagement for developing regulations Voter turnout
Unit                                          Average Score    Percentage
0                                                       2.7            92
1                                                       1.3            76
2                                                         2            88
3                                                       2.9            68
4                                                       1.3            47

Group              Health                      Life Satisfaction  \
Indicator Life expectancy Self-reported health Life satisfaction
Unit                Years           Percentage     Average Score
0                    83.0                   85               7.1
1                    82.0                   71               7.2
2                    82.1                   74               6.8
3                    82.1                   89               7.0
4                    80.6                   60               6.2

Group                                  Safety                \
Indicator Feeling safe walking alone at night Homicide rate
Unit                               Percentage         Ratio
0                                          67           0.9
1                                          86           0.5
2                                          56           1.1
3                                          78           1.2
4                                          41           2.4

Group                     Work-Life Balance                                 \
Indicator Employees working very long hours Leisure and personal care time
Unit                             Percentage                          Hours
0                                      12.5                          14.36
1                                       5.3                          14.51
2                                       4.3                          15.52
3                                       3.3                          14.57
4                                       7.7                             ..

Group     Colour
Indicator
Unit
0           None
1           None
2           None
3           None
4           None

[5 rows x 26 columns]

In [16]:
# For each country, give it a distinct colour
for index, row in modified_df.iterrows():
    modified_df.at[index, 'Colour'] = distinct_colours[index]

In [17]:
# Save modified df to a new excel file
modified_df.to_excel("wrangled_df.xlsx")

In [18]:
# For now, use random imputation to populate empty fields so that the visualization can be worked on
for column in modified_df.columns:
    # Replace '...' being used to denote empty fields with numpy NaN value
    modified_df[column] = modified_df[column].replace('..', np.nan)

    # For each column check to see if there are any empty fields
    if modified_df[column].isna().any():
        # List of existing values
        existing_values = modified_df[column].dropna().values
        # Dataframe of rows where values are missing
        missing_rows = modified_df[column].isna()
        # Randomly select existing values to populate missing rows
        modified_df.loc[missing_rows, column] = np.random.choice(existing_values, size=missing_rows.sum())

In [19]:
modified_df.head(50)

Group                       Country                        Housing  \
Indicator                           Dwellings w/o basic facilities
Unit                                                    Percentage
0                         Australia                            0.4
1                           Austria                            0.8
2                           Belgium                            0.7
3                            Canada                            0.2
4                             Chile                            9.4
5                          Colombia                           12.3
6                        Costa Rica                            2.3
7                           Czechia                            0.5
8                           Denmark                            0.5
9                           Estonia                            5.7
10                          Finland                            0.4
11                           France                            0.5
12                          Germany                            0.1
13                           Greece                            0.4
14                          Hungary                            3.5
15                          Iceland                            0.0
16                          Ireland                            0.2
17                           Israel                            0.7
18                            Italy                            0.6
19                            Japan                            6.4
20                      South Korea                            2.5
21                           Latvia                           11.2
22                        Lithuania                           11.8
23                       Luxembourg                            0.1
24                           Mexico                           25.9
25                      Netherlands                            0.1
26                      New Zealand                           12.3
27                           Norway                            0.0
28                           Poland                            2.3
29                         Portugal                            0.9
30                         Slovakia                            1.5
31                         Slovenia                            0.2
32                            Spain                            0.3
33                           Sweden                            0.0
34                      Switzerland                            0.0
35                           Turkey                            4.9
36                   United Kingdom                            0.5
37         United States of America                            0.1
39                           Brazil                            6.7
40                           Russia                           13.8
41                     South Africa                           35.9

Group                                           \
Indicator Housing expenditure Rooms per person
Unit               Percentage            Ratio
0                        19.4              1.8
1                        20.8              1.6
2                        20.0              2.1
3                        22.9              2.6
4                        18.4              1.9
5                        18.1              1.0
6                        17.0              1.2
7                        23.4              1.5
8                        23.3              1.9
9                        17.0              1.7
10                       23.1              1.9
11                       20.7              1.8
12                       20.0              1.8
13                       21.8              1.2
14                       19.9              1.4
15                       21.8              1.6
16                       20.6              2.1
17                       18.3              1.2
18                       22.5              1.4
19                       21.8              1.9
20                       14.7              1.5
21                       20.8              1.2
22                       18.4              1.5
23                       20.7              2.0
24                       17.8              1.1
25                       19.6              2.0
26                       25.0              2.4
27                       17.7              2.1
28                       21.2              1.1
29                       19.6              1.7
30                       27.4              1.1
31                       18.2              1.6
32                       21.7              1.9
33                       20.1              1.7
34                       21.4              1.9
35                       18.9              1.0
36                       23.2              2.0
37                       18.3              2.4
39                       23.2              1.9
40                       17.4              1.0
41                       18.1              1.9

Group                                       Income                       \
Indicator Household net adjusted disposable income Household net wealth
Unit                                     US Dollar            US Dollar
0                                          37433.0             528768.0
1                                          37001.0             309637.0
2                                          34884.0             447607.0
3                                          34421.0             478240.0
4                                          37001.0             135787.0
5                                          16517.0             233286.0
6                                          16517.0             684500.0
7                                          26664.0              79245.0
8                                          33774.0             149864.0
9                                          23784.0             188627.0
10                                         33471.0             230032.0
11                                         34375.0             298639.0
12                                         38971.0             304317.0
13                                         20791.0             148323.0
14                                         21026.0             150296.0
15                                         34984.0             370341.0
16                                         29488.0             370341.0
17                                         23784.0             309637.0
18                                         29431.0             295020.0
19                                         28872.0             294735.0
20                                         24590.0             362340.0
21                                         19783.0              79245.0
22                                         26976.0             182039.0
23                                         44773.0             941162.0
24                                         16269.0              79245.0
25                                         34984.0             248599.0
26                                         39024.0             514162.0
27                                         39144.0             268358.0
28                                         23675.0             233221.0
29                                         24877.0             255303.0
30                                         21149.0             171425.0
31                                         25250.0             233286.0
32                                         27155.0             366534.0
33                                         33730.0             941162.0
34                                         39697.0             233221.0
35                                         39144.0             298639.0
36                                         33049.0             524422.0
37                                         51147.0             684500.0
39                                         21149.0             684500.0
40                                         19546.0             233221.0
41                                          9338.0             514162.0

Group                         Jobs                  \
Indicator Labour market insecurity Employment rate
Unit                    Percentage      Percentage
0                              3.1              73
1                              2.3              72
2                              2.4              65
3                              3.8              70
4                              7.0              56
5                              4.5              58
6                              4.5              55
7                              2.3              74
8                              4.5              74
9                              5.4              74
10                             2.2              72
11                             3.1              65
12                             1.4              77
13                            21.7              56
14                             3.8              70
15                             1.0              78
16                             2.6              68
17                             4.6              67
18                             8.6              58
19                             2.7              77
20                             2.9              66
21                             6.3              72
22                             8.6              72
23                             2.2              67
24                             4.0              59
25                             2.5              78
26                             4.5              77
27                             2.8              75
28                             5.0              69
29                             8.1              69
30                             8.8              68
31                             5.9              71
32                            15.8              62
33                             4.4              75
34                             2.5              80
35                            13.0              48
36                             3.3              75
37                             4.2              67
39                            21.7              57
40                             3.8              70
41                             3.8              39

Group                                                    ...  \
Indicator Long-term unemployment rate Personal earnings  ...
Unit                       Percentage         US Dollar  ...
0                                 1.0           55206.0  ...
1                                 1.3           53132.0  ...
2                                 2.3           54327.0  ...
3                                 0.5           55342.0  ...
4                                 1.0           26729.0  ...
5                                 1.1           38515.0  ...
6                                 1.5           37769.0  ...
7                                 0.6           29885.0  ...
8                                 0.9           58430.0  ...
9                                 1.2           30720.0  ...
10                                1.2           46230.0  ...
11                                2.9           45581.0  ...
12                                1.2           53745.0  ...
13                               10.8           27207.0  ...
14                                1.2           25409.0  ...
15                                0.7           67488.0  ...
16                                1.2           49474.0  ...
17                                0.2           39322.0  ...
18                                4.8           37769.0  ...
19                                0.8           38515.0  ...
20                                0.0           41960.0  ...
21                                2.2           29876.0  ...
22                                2.5           31811.0  ...
23                                1.7           65854.0  ...
24                                0.1           16230.0  ...
25                                0.9           58828.0  ...
26                                0.4           45269.0  ...
27                                0.9           55780.0  ...
28                                0.6           32527.0  ...
29                                2.3           28410.0  ...
30                                3.0           23619.0  ...
31                                1.9           41445.0  ...
32                                5.0           37922.0  ...
33                                1.0           47020.0  ...
34                                1.7           64824.0  ...
35                                3.3           45269.0  ...
36                                0.9           47147.0  ...
37                                0.5           69392.0  ...
39                                0.2           54327.0  ...
40                                1.1           26729.0  ...
41                               17.9           58828.0  ...

Group                                      Civic Engagement                \
Indicator Stakeholder engagement for developing regulations Voter turnout
Unit                                          Average Score    Percentage
0                                                       2.7            92
1                                                       1.3            76
2                                                       2.0            88
3                                                       2.9            68
4                                                       1.3            47
5                                                       1.4            53
6                                                       1.8            66
7                                                       1.6            62
8                                                       2.0            85
9                                                       2.7            64
10                                                      2.2            69
11                                                      2.1            75
12                                                      1.8            76
13                                                      1.8            58
14                                                      1.2            70
15                                                      2.1            81
16                                                      1.3            63
17                                                      2.5            67
18                                                      2.5            73
19                                                      1.4            53
20                                                      2.9            77
21                                                      2.2            55
22                                                      2.4            57
23                                                      1.7            90
24                                                      3.2            63
25                                                      2.6            79
26                                                      2.5            82
27                                                      2.2            78
28                                                      2.6            68
29                                                      1.5            49
30                                                      3.0            66
31                                                      2.5            53
32                                                      1.8            72
33                                                      2.0            87
34                                                      2.3            45
35                                                      1.5            86
36                                                      3.1            68
37                                                      3.1            65
39                                                      2.2            80
40                                                      2.0            68
41                                                      2.9            66

Group              Health                      Life Satisfaction  \
Indicator Life expectancy Self-reported health Life satisfaction
Unit                Years           Percentage     Average Score
0                    83.0                 85.0               7.1
1                    82.0                 71.0               7.2
2                    82.1                 74.0               6.8
3                    82.1                 89.0               7.0
4                    80.6                 60.0               6.2
5                    76.7                 80.0               5.7
6                    80.5                 73.0               6.3
7                    79.3                 62.0               6.9
8                    81.5                 70.0               7.5
9                    78.8                 57.0               6.5
10                   82.1                 68.0               7.9
11                   82.9                 67.0               6.7
12                   81.4                 66.0               7.3
13                   81.7                 79.0               5.8
14                   76.4                 58.0               6.0
15                   83.2                 77.0               7.6
16                   82.8                 84.0               7.0
17                   82.9                 74.0               7.2
18                   83.6                 73.0               6.5
19                   84.4                 37.0               6.1
20                   83.3                 34.0               5.8
21                   75.5                 47.0               6.2
22                   76.4                 46.0               6.4
23                   82.7                 72.0               7.4
24                   75.1                 66.0               6.0
25                   82.2                 75.0               7.5
26                   82.1                 86.0               7.3
27                   83.0                 75.0               7.3
28                   78.0                 60.0               6.1
29                   81.8                 50.0               5.8
30                   77.8                 65.0               6.5
31                   81.6                 67.0               6.5
32                   83.9                 75.0               6.5
33                   83.2                 76.0               7.3
34                   84.0                 81.0               7.5
35                   78.6                 67.0               4.9
36                   81.3                 73.0               6.8
37                   78.9                 88.0               7.0
39                   75.9                 85.0               6.1
40                   73.2                 43.0               5.5
41                   64.2                 70.0               4.9

Group                                  Safety                \
Indicator Feeling safe walking alone at night Homicide rate
Unit                               Percentage         Ratio
0                                          67           0.9
1                                          86           0.5
2                                          56           1.1
3                                          78           1.2
4                                          41           2.4
5                                          50          23.1
6                                          47          10.0
7                                          77           0.7
8                                          85           0.5

In [20]:
# Replace NaN values that have filled empty cells back to empty string for Excel, as not doing this causes some errors such as adding new rows of ony NaN values.
modified_df = modified_df.replace(np.nan, '', regex=True)

# Save the wrangled dataframe with randomly imputated values as an excel file to be loaded on and worked with in another notebook
modified_df.to_excel("wrangled_df_ri.xlsx")